# Generated by Django 5.2.7 on 2025-10-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('R', 'Unpaid'), ('P', 'Paid')], default='R', max_length=1)),
                ('form_url', models.URLField()),
                ('image_url', models.URLField()),
                ('visibility', models.CharField(choices=[('Pub', 'Public'), ('Pri', 'Private')], default='Pub', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('logo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('registration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.registration')),
                ('status', models.CharField(choices=[('C', 'C'), ('D', 'D')], default='D', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('event.registration',),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('registration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.registration')),
                ('status', models.CharField(choices=[('T', 'T'), ('F', 'F')], default='F', max_length=1)),
                ('stripe_id', models.CharField(max_length=100)),
            ],
            bases=('event.registration',),
        ),
        migrations.AddField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.university'),
        ),
        migrations.AddField(
            model_name='event',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.university'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'event')},
        ),
    ]
