# Generated by Django 5.2.7 on 2025-10-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
