# Generated by Django 5.2.7 on 2025-10-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
