# Generated by Django 5.2.7 on 2025-10-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_createdat_event_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rsvp',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'managed': False},
        ),
    ]
