# Generated by Django 5.2.7 on 2025-10-25 08:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_registration_and subclasses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rsvp',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
    ]
