# Generated by Django 5.2.7 on 2025-10-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_delete_admin_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'event')},
        ),
    ]
