# Generated by Django 5.2.7 on 2025-10-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_registration_unique_together_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
