# Generated by Django 5.2.7 on 2025-11-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_registration_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
    ]
